### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by rezabahrami776** [M0tHs3C/Hikxploit#2]
Hello . Please make tutorial about this tool

**Comment by M0tHs3C** [comment]
I will looking forward to make one tomorrow

Il mer 11 set 2019, 23:05 rezabahrami776 <notifications@github.com> ha
scritto:

**Comment by M0tHs3C** [comment]
i left a written tutorial on the readme page, enjoy
feel free to reply

**Comment by rezabahrami776** [comment]
thank you so mach
