### ISSUE TITLE
API Key Issue

### ISSUE THREAD

**Issue by ghost** [M0tHs3C/Hikxploit#3]
Could anyone help me i am getting this error when i run "python hikxploit.py" and press 1 and type something. I have put my Shodan API key inside the api.txt file on the first line.

`
Traceback (most recent call last):
  File "hikxploit.py", line 347, in <module>
    main()
  File "hikxploit.py", line 344, in main
    response()
  File "hikxploit.py", line 306, in response
    gather_host_shodan()
  File "hikxploit.py", line 63, in gather_host_shodan
    response = api.search(query)
  File "/home/connor/.local/lib/python2.7/site-packages/shodan/client.py", line 498, in search
    return self._request('/shodan/host/search', args)
  File "/home/connor/.local/lib/python2.7/site-packages/shodan/client.py", line 321, in _request
    raise APIError(error)
shodan.exception.APIError: Invalid API key
`

**Comment by harangutang** [comment]
Me too. I'll let you know if I find a workaround

**Comment by M0tHs3C** [comment]
there no work around, you are entering a wrong API key or u don't have a
valid API key
or maybe you are copy pasting it wrong, boy I hope not

Il gio 9 apr 2020, 20:39 harangutang <notifications@github.com> ha scritto:

**Comment by harangutang** [comment]
I can confirm that there is a bug, and I found a workaround. Even with a valid api key in api.txt, it throws an error per the original post. I replaced line 52 of hikxploit.py with 

api_shodan_key = "_my_apikey_"

And everything worked ok after that.

**Comment by M0tHs3C** [comment]
yeah, that would definitely will work
as the raw_input() function
the only problem is if you crop a space before or after
or you manually modify the API key file

Il ven 10 apr 2020, 09:06 harangutang <notifications@github.com> ha scritto:

**Comment by harangutang** [comment]
I see. Yes I did edit mine manually. Anyway, thanks for creating and maintaining this software!

**Comment by M0tHs3C** [comment]
thank you for using it, didn't expect someone to be actually using it

Il ven 10 apr 2020, 09:16 harangutang <notifications@github.com> ha scritto:

**Comment by M0tHs3C** [comment]
hikkxploit moved to argo
closing this issue
